name: test-read-files

on:
  push:
    branch:
      - ['**']

jobs:
  readfile:
    name: test
    runs-on: ubuntu-latest
    outputs:
      dockerhub_repo: ${{steps.dockerhub.outputs.repo}}
      dockerhub_image:  ${{steps.dockerhub.outputs.image}}
    steps:
    - uses: actions/checkout@v2
    - name: Read setup file
      id: read 
      run: |
        echo 'SETUP_YAML<<EOF' >> $GITHUB_ENV
        cat setup.yaml >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
        cat $GITHUB_ENV
    - name: parse setup yaml 
      run: |
        echo repo=${{fromJson(env.SETUP_YAML).dockerhub_repo}}
        echo image=${{fromJson(env.SETUP_YAML).dockerhub_image}}
    - 
      name: parse setup yaml 
      id: dockerhub
      run: |
        echo  "::set-output name=repo::${{fromJson(env.SETUP_YAML).dockerhub_repo}}"
        echo  "::set-output name=image::${{fromJson(env.SETUP_YAML).dockerhub_image}}"
  usevars:
    runs-on: ubuntu-latest
    needs: readfile
    steps:
    - run: |
        echo ${{needs.readfile.outputs.dockerhub_repo}}
        echo ${{needs.readfile.outputs.dockerhub_image}}


